version: '3.8'
services:
  ddb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: "ddb-local"
    ports:
      - "8000:8000"
    healthcheck:
      test: [
        "CMD-SHELL",
        'if [ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]; then exit 0; else exit 1; fi',
      ]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
        - "./docker/ddb-local:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  janus:
    build: .
    env_file: local.env
    ports:
      - "8001:8001"
    depends_on:
      - cache
      - ddb-local
volumes:
  cache:
    driver: local
