version: '3.8'
services:
  ddb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: "ddb-local"
    ports:
      - "8000:8000"
    healthcheck:
      test: [
        "CMD-SHELL",
        'if [ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]; then exit 0; else exit 1; fi',
      ]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
        - "./docker/ddb-local:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root
  mq:
    hostname: 'mq'
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - "./docker/rabbitmq/data/:/var/lib/rabbitmq/"
      - "./docker/rabbitmq/data/:/var/log/rabbitmq"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 30s
      timeout: 30s
      retries: 5
  janus:
    build: .
    env_file: local.env
    ports:
      - "8001:8001"
    depends_on:
      mq:
        condition: service_healthy
      ddb-local:
        condition: service_healthy


