version: '3.8'
services:
  ddb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: "ddb-local"
    ports:
      - "8000:8000"
    healthcheck:
      test: [
        "CMD-SHELL",
        'if [ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]; then exit 0; else exit 1; fi',
      ]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
        - "./docker/ddb-local:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root
  janus:
    build: .
    env_file: local.env
    ports:
      - "8001:8001"
    depends_on:
      ddb-local:
        condition: service_healthy
